### ISSUE TITLE
Cannot convert empty strings (or whitespace) to float

### ISSUE THREAD

**Issue by gbella** [opendatatrentino/OpenDataRise#108]
If a cell in a lat/long column is empty (or contains whitespace) then conversion fails on it.
The cell will contain the following red text:
"Couldn't cast value of Java class java.lang.String to datatype xsd:float (with locale en). REASON: "

The expected behaviour should be to leave the cell text as blank.

**Comment by DavidLeoni** [comment]
hope it's fixed in branch-0.3  

there is not just null -> Float to worry about, could be empty string, string with a space, Dict with only one string, SemText with a space, etc....
