### ISSUE TITLE
Bug with matching to all column in disambiguation panel

### ISSUE THREAD

**Issue by gbella** [opendatatrentino/OpenDataRise#109]
Bug with mass disambiguation in column: clicking on “Match all matching words in column” results in an error message “Couldn't reconstruct the operation!”. This is for the word “LABORATORIO”. One-by-one disambiguation works.
project=1990896200502 (gabor)

**Comment by DavidLeoni** [comment]
I tried disambiguating savagely on punti di prelievo (which I believe is the dataset you used) but couldn't reproduce. Closing it for now.
