### ISSUE TITLE
Publication to ckan should be optional

### ISSUE THREAD

**Issue by DavidLeoni** [opendatatrentino/OpenDataRise#148]

**Comment by DavidLeoni** [comment]
Closed in dev-0.3

Also implemented batchbox, a prototype of UI to execute batch operations:

![step6-1](https://cloud.githubusercontent.com/assets/628313/12978515/a75bbb6c-d0d1-11e5-9a30-64aaae35d58b.png)

**Comment by gbella** [comment]
TypeError: step6Panel_1.datasetTitleLabel is undefined
step6Panel_1.datasetTitleLabel.text($.i18n._("step-6-1")["dataset-title"]);

**Comment by DavidLeoni** [comment]
Error in dev-0.3 branch was due to a botched merge from feature branch, should be fixed now
