### ISSUE TITLE
Cannot introduce new column

### ISSUE THREAD

**Issue by gbella** [opendatatrentino/OpenDataRise#98]
In step 2 there is no direct way to map an etype attribute to a column created and filled in by the user.
This is a very important feature, e.g., for the class attribute.

**Comment by DavidLeoni** [comment]
Closed in dev-0.3

Now in the sources menu for mappings there  is  a 'New custom source...' option. Each custom source can be given a name and once created also reused as common source for splits. Name is asked only when mapping is completed with the target, which is not optimal but works for our purposes.
